# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fatfreecrm

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fatfreecrmregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_db1106f9b87b467bb077d754be0f3ef0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a7f04377c14f46989511b99c11e6afa1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: fatfreecrmregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_db1106f9b87b467bb077d754be0f3ef0 }}/fat_free_crm-web:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fatfreecrm'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_80cbce9a6d5f42368d867c1e7fb8d124 }}
        images: 'fatfreecrmregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_db1106f9b87b467bb077d754be0f3ef0 }}/fat_free_crm-web:${{ github.sha }}'